### ISSUE TITLE
The version in setup.py is incompatible with actual version

### ISSUE THREAD

**Issue by lstolcman** [sirk390/wxasync#14]
The version in setup.py is incompatible with actual version:
https://github.com/sirk390/wxasync/blob/ec9a80b92a69efc482246905fd87795fac14d877/setup.py#L4
https://github.com/sirk390/wxasync/releases/tag/0.43

**Comment by sirk390** [comment]
Thanks for seeing the issue :) I forgot to push the local change I made

**Comment by sirk390** [comment]
It should be fixed. Tell me if it is ok for you here
