### ISSUE TITLE
App.OnExit() isn't called

### ISSUE THREAD

**Issue by topic2k** [sirk390/wxasync#30]
<details>
<summary>Versions</summary>

```
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
wxasync 0.49
wxPython 4.2.2a1.dev5600+b67eef25 msw (phoenix) wxWidgets 3.2.2.1
```

</details>

As the title says, `OnExit()` isn't called when exiting the app. Without wxasync, `OnExit()` is called.

<details>
<summary>wxasync demo code</summary>

```python
import wxasync
import wx
import asyncio


class MyApp(wxasync.WxAsyncApp):

    def OnExit(self):
        print("OnExit called")
        return 0


async def main():
    app = MyApp()
    frame = wx.Frame(None)
    frame.Show()
    await app.MainLoop()


asyncio.run(main())
```

</details>

<details>
<summary>wxPython demo code</summary>

```python
import wx


class MyApp(wx.App):

    def OnExit(self):
        print("OnExit called")
        return 0


app = MyApp()
frame = wx.Frame(None)
frame.Show()
app.MainLoop()
```

</details>

**Comment by sirk390** [comment]
Hi @topic2k, thanks for the issue. What do you think about the fix like this https://github.com/sirk390/wxasync/commit/3ecfe3615af7871ce75a1154e1b84c87c6380680 ? Any other event missing?

**Comment by topic2k** [comment]
Yes, that's working. Thank you.
