### ISSUE TITLE
Python 3.8 CancelledError

### ISSUE THREAD

**Issue by rbotman** [sirk390/wxasync#6]
Python 3.8 included a change to the base class for CancelledError.
See: https://bugs.python.org/issue32528

Just removing '.futures' from line 5 avoids an error in 3.8
`from asyncio.futures import CancelledError`

Here's the error:
ImportError: cannot import name 'CancelledError' from 'asyncio.futures'

**Comment by sirk390** [comment]
Fixed in version 0.41, commit 7f38f419805882b05c3f1e3eda5234d2a2f3a7aa
