### ISSUE TITLE
Pass parameters to StartCoroutine

### ISSUE THREAD

**Issue by petrasovaa** [sirk390/wxasync#8]
It would be convenient to pass parameters to the coroutine function, which is not possible now as far as I can tell.

**Comment by sirk390** [comment]
Hi, I think you can already.  StartCoroutine accepts either a "coroutine" either a "coroutine function".
So you can do:
      StartCoroutine(self.update_clock(arg1, arg2), self)
Does this work for you?
If might not be so clear though. Maybe I should add some documentation

**Comment by petrasovaa** [comment]
You are right, I missed that, thanks!
